char cQuestion[][64] = {
    "move right" , 
    "move left" , 
    "move up" , 
    "move down" , 
    "open command history",
    "past register",
    "add a new blank line below",
    "add a new blank line up",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
    "this is a test , answer is A",
};

char cAnswer[][64] = {
    "l",
    "h",
    "k",
    "j",
    "q:",
    "\"+",
    "o",
    "O",
    "A",
    "A",
    "A",
    "A",
    "A",
    "A",
    "A",
    "A",
    "A",
    "A",
};

